### ISSUE TITLE
Language change broken after the last update

### ISSUE THREAD

**Issue by Tobe2d** [Zeyi-Lin/HivisionIDPhotos#121]
When trying to change the lang to eng it make error.
it was working perfictly before the last update.

![image](https://github.com/user-attachments/assets/83634555-bc71-4540-a956-09feb0310ffd)

Log
```
Traceback (most recent call last):
  File "F:\HivisionIDPhotos\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\HivisionIDPhotos\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\HivisionIDPhotos\venv\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "F:\HivisionIDPhotos\venv\lib\site-packages\gradio\blocks.py", line 1708, in postprocess_data
    predictions = convert_component_dict_to_list(
  File "F:\HivisionIDPhotos\venv\lib\site-packages\gradio\blocks.py", line 645, in convert_component_dict_to_list
    raise ValueError(
ValueError: Returned component <gradio.components.radio.Radio object at 0x0000023CE4044640> not specified as output of function.
```

**Comment by Zeyi-Lin** [comment]
Saw this issue, already fixed.

**Comment by Tobe2d** [comment]
Yes, it is working now, and even it show more languages ;-)
