### ISSUE TITLE
按照教程运行python app.py的时候出现了错误OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址

### ISSUE THREAD

**Issue by pmQAQ** [Zeyi-Lin/HivisionIDPhotos#124]
C:\Users\PMgood\Anaconda3\envs\photo\python.exe C:\Users\PMgood\Desktop\tools\HivisionIDPhotos\app.py 
Running on local URL:  http://127.0.0.1:7860
Accept failed on a socket
socket: <asyncio.TransportSocket fd=1352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 7860)>
Traceback (most recent call last):
  File "C:\Users\PMgood\Anaconda3\envs\photo\lib\asyncio\proactor_events.py", line 825, in loop
    conn, addr = f.result()
  File "C:\Users\PMgood\Anaconda3\envs\photo\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\PMgood\Anaconda3\envs\photo\lib\asyncio\windows_events.py", line 575, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Users\PMgood\Anaconda3\envs\photo\lib\asyncio\windows_events.py:577> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "C:\Users\PMgood\Anaconda3\envs\photo\lib\asyncio\windows_events.py", line 580, in accept_coro
    await future
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

像请教一下怎么解决

**Comment by fangkk0168** [comment]
1、检查下python版本。要求：Python >= 3.7（项目主要测试在 python 3.10）
2、重新clone项目，然后 安装依赖环境，下载权重文件重新试下。
