### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by fdzl22** [Zeyi-Lin/HivisionIDPhotos#159]
我有一个问题，为什么我在vscode中直接点击运行会出现报错，显示缺少cv2：
[Running] python -u "c:\Users\11438\HivisionIDPhotos\app.py"
Traceback (most recent call last):
  File "c:\Users\11438\HivisionIDPhotos\app.py", line 3, in <module>
    from demo.processor import IDPhotoProcessor
  File "c:\Users\11438\HivisionIDPhotos\demo\processor.py", line 2, in <module>
    from hivision import IDCreator
  File "c:\Users\11438\HivisionIDPhotos\hivision\__init__.py", line 1, in <module>
    from .creator import IDCreator, Params as IDParams, Result as IDResult
  File "c:\Users\11438\HivisionIDPhotos\hivision\creator\__init__.py", line 12, in <module>
    import hivision.creator.utils as U
  File "c:\Users\11438\HivisionIDPhotos\hivision\creator\utils.py", line 10, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

[Done] exited with code=1 in 0.346 seconds

但是我在终端中没有这个问题，可以正常运行。我使用conda作为虚拟运行环境

**Comment by Zeyi-Lin** [comment]
检查一下你VSCode直接运行使用的虚拟环境与终端是否一致

**Comment by fdzl22** [comment]
是的，我发现了，因为我安装了conda，conda下载时有个设置是默认使用python3.12作为所有的默认运行环境，但是我没有点它造成了cmd中的环境和vscode直接运行的环境不行同，即使我在vscode中也使用了conda作为运行环境，但是还是在和我python下载路径的环境相同，均是python3.10。
