### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 21: illegal multibyte sequence。之前能正常运行，今天突然这样了

### ISSUE THREAD

**Issue by xlxxlup** [Zeyi-Lin/HivisionIDPhotos#181]
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    size_list_dict_CN = csv_to_size_list(os.path.join(root_dir, "size_list_CN.csv"))
  File "D:\ModeCode\HivisionIDPhotos\HivisionIDPhotos\data_utils.py", line 12, in csv_to_size_list
    next(reader)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 21: illegal multibyte sequence

**Comment by maocatooo** [comment]
你应该是在windwos上重新编辑保存了csv，导致csv的编码是gbk了，使用工具转换一下就可以了
