### ISSUE TITLE
运行app.py时出现TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Smart-ab** [Zeyi-Lin/HivisionIDPhotos#184]
hivision\plugin\beauty\lut/lut_origin.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from demo.processor import IDPhotoProcessor
  File "C:\Users\stone\Desktop\HivisionIDPhotos\demo\processor.py", line 2, in <module>
    from hivision import IDCreator
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\__init__.py", line 1, in <module>
    from .creator import IDCreator, Params as IDParams, Result as IDResult
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\creator\__init__.py", line 16, in <module>
    from hivision.plugin.beauty.handler import beauty_face
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\__init__.py", line 1, in <module>
    from .beauty_tools import BeautyTools
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\beauty_tools.py", line 10, in <module>
    from .whitening import MakeWhiter
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\whitening.py", line 50, in <module>
    make_whiter = MakeWhiter(default_lut)
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\whitening.py", line 38, in __init__
    self.lut_white = LutWhite(lut_image)
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\whitening.py", line 14, in __init__
    self.lut = self._create_lut(lut_image)
  File "C:\Users\stone\Desktop\HivisionIDPhotos\hivision\plugin\beauty\whitening.py", line 24, in _create_lut
    cube64 = lut_image[cy : cy + self.CUBE64_SIZE, cx : cx + self.CUBE64_SIZE]
TypeError: 'NoneType' object is not subscriptable

**Comment by lmf112358** [comment]
同问为什么打不开lug_image
[ WARN:0@5.239] global loadsave.cpp:241 cv::findDecoder imread_('F:\工具\github_clone\HivisionIDPhotos\hivision\plugin\beauty\lut/lut_origin.png'): can't open/read file: check file path/integrity

**Comment by han-ry19** [comment]
路径里不能有中文
