### ISSUE TITLE
按照demo命令运行报错

### ISSUE THREAD

**Issue by shen774411223d** [Zeyi-Lin/HivisionIDPhotos#51]
我的py环境为 **3.10.14**
.onnx文件已经放到根目录，目前还没排查出问题 请大佬指教
执行 `python inference.py -i images/test.jpg -o ./idphoto.png -s '(413,295)'`
```
正在加载抠图模型...
抠图采用本地模型
image_matting 函数花费的时间为 0.22.
face_number_detection_mtcnn 函数花费的时间为 0.32.
Traceback (most recent call last):
  File "C:\Users\49201\working\HivisionIDPhotos\inference.py", line 57, in <module>
    ) = IDphotos_create(
  File "C:\Users\49201\working\HivisionIDPhotos\hivisionai\hycv\vision.py", line 19, in wrapper
    return_param = func(*args, **kw)
  File "C:\Users\49201\working\HivisionIDPhotos\src\face_judgement_align.py", line 638, in IDphotos_create
    result_image_hd, result_image_standard, clothing_params = idphoto_cutting(
  File "C:\Users\49201\working\HivisionIDPhotos\hivisionai\hycv\vision.py", line 36, in wrapper
    return_param = func(*args, **kw)
  File "C:\Users\49201\working\HivisionIDPhotos\src\face_judgement_align.py", line 376, in idphoto_cutting
    width_height_ratio = standard_size[0] / standard_size[1]  # 高宽比
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

执行 `python inference.py -t add_background -i ./idphoto.png -o ./idhoto_ab.jpg  -c '(0,0,0)' -k 30`
```
正在加载抠图模型...
[ WARN:0@0.620] global loadsave.cpp:244 cv::findDecoder imread_('./idphoto.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\49201\working\HivisionIDPhotos\inference.py", line 89, in <module>
    result_image = add_background(input_image, bgr=color)
  File "C:\Users\49201\working\HivisionIDPhotos\hivisionai\hycv\vision.py", line 302, in add_background
    height, width = input_image.shape[0], input_image.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
```

执行 `python inference.py -t generate_layout_photos -i ./idhoto_ab.jpg -o ./idhoto_layout.jpg  -s '(413,295)' -k 200`
```
正在加载抠图模型...
[ WARN:0@0.621] global loadsave.cpp:244 cv::findDecoder imread_('./idhoto_ab.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\49201\working\HivisionIDPhotos\inference.py", line 106, in <module>
    typography_arr, typography_rotate = generate_layout_photo(
  File "C:\Users\49201\working\HivisionIDPhotos\src\layoutCreate.py", line 70, in generate_layout_photo
    layout_mode, centerBlockWidth, centerBlockHeight = judge_layout(input_width, input_height, PHOTO_INTERVAL_W,
  File "C:\Users\49201\working\HivisionIDPhotos\src\layoutCreate.py", line 12, in judge_layout
    centerBlockHeight_temp = input_height * i + PHOTO_INTERVAL_H * (i-1)
TypeError: can only concatenate str (not "int") to str
```

**Comment by Zeyi-Lin** [comment]
在inference中去掉-s参数，可以work吗？

我在今天在windows主机上完整测试一下接口

**Comment by shen774411223d** [comment]
> 在inference中去掉-s参数，可以work吗？
> 
> 我今天在windows主机上完整测试一下接口

你好，按照您的解决办法 去掉-s是可以生成透明底色图片的。
但是第二步 又出现新的错误
我的执行命令 `python inference.py -t add_background -i ./idphoto.png -o ./idhoto_ab.jpg  -c '(0,0,0)' -k 30`
```
正在加载抠图模型...
Traceback (most recent call last):
  File "C:\Users\49201\working\HivisionIDPhotos\inference.py", line 89, in <module>
    result_image = add_background(input_image, bgr=color)
  File "C:\Users\49201\working\HivisionIDPhotos\hivisionai\hycv\vision.py", line 307, in add_background
    b2 = np.full([height, width], bgr[0], dtype=int)
  File "C:\Users\49201\miniconda3\envs\py3100\lib\site-packages\numpy\core\numeric.py", line 345, in full
    multiarray.copyto(a, fill_value, casting='unsafe')
  File "<__array_function__ internals>", line 200, in copyto
ValueError: invalid literal for int() with base 10: ','
```

**Comment by Zeyi-Lin** [comment]
大概知道了问题 预计在下午or晚上修复

**Comment by Zeyi-Lin** [comment]
Inference与API接口已更新，可按照新的README指引重新试试

**Comment by shen774411223d** [comment]
> Inference与API接口已更新，可按照新的README指引重新试试

按照新的指引已经成功运行了 非常感谢！
