### ISSUE TITLE
HivisionIDPhotos Api调用问题

### ISSUE THREAD

**Issue by OuTaMan** [Zeyi-Lin/HivisionIDPhotos#98]
INFO:     [127.0.0.1:52124](http://127.0.0.1:52124/) - "POST /add_background HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await [self.app](http://self.app/)(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await [self.app](http://self.app/)(scope, receive, _send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions([self.app](http://self.app/), conn)(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 295, in handle
    await [self.app](http://self.app/)(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\home\项目\HivisionIDPhotos-1.2.1\deploy_api.py", line 116, in photo_add_background
    result_image = add_background(
                   ^^^^^^^^^^^^^^^
  File "G:\home\项目\HivisionIDPhotos-1.2.1\hivision\utils.py", line 259, in add_background
    b, g, r, a = cv2.split(input_image)
    ^^^^^^^^^^

请问调用api  add_background 这个接口后报ASGI这个错误 是什么原因

**Comment by Zeyi-Lin** [comment]
add background这个接口做的事情是将idphoto接口得到的透明图加上背景色，所以你需要输入的是一张透明底png图像

**Comment by OuTaMan** [comment]
单独调用 idphoto 接口
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zdy\AppData\Local\anaconda3\Lib\site-packages\fastapi\routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\home\项目\HivisionIDPhotos-1.2.1\deploy_api.py", line 50, in idphoto_inference
    result = creator(
             ^^^^^^^^
  File "G:\home\项目\HivisionIDPhotos-1.2.1\hivision\creator\__init__.py", line 102, in __call__
    adjust_photo(ctx)
  File "G:\home\项目\HivisionIDPhotos-1.2.1\hivision\creator\photo_adjuster.py", line 31, in adjust_photo
    face_measure / params.head_measure_ratio
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by OuTaMan** [comment]
我应该找到问题在哪了

**Comment by OuTaMan** [comment]
> 增加背景這個介面要做的事情是idphoto介面得到的透明圖加上背景色，所以需要輸入一張透明底png圖片
请问单独调用 idphoto 接口 报的这个错是什么原因

**Comment by Zeyi-Lin** [comment]
> > 增加背景這個介面要做的事情是idphoto介面得到的透明圖加上背景色，所以需要輸入一張透明底png圖片
> > 请问单独调用 idphoto 接口 报的这个错是什么原因

完整的调用接口方式代码，以及测试图片可以发一下，方便排查问题

**Comment by OuTaMan** [comment]
![image](https://github.com/user-attachments/assets/6f0e0280-7bae-416f-a606-203f65040eba)
![test0](https://github.com/user-attachments/assets/18c7462d-9846-47c5-b465-edb14af7a81a)

**Comment by OuTaMan** [comment]
> > > 增加背景這個介面要做的事情是idphoto介面得到的透明圖加上背景色，所以需要輸入一張透明底png圖片
> > > 请问单独调用 idphoto 接口 报的这个错是什么原因
> 
> 完整的调用接口方式代码，以及测试图片可以发一下，方便排查问题

参数都是用默认的

**Comment by Zeyi-Lin** [comment]
> > > > 增加背景這個介面要做的事情是idphoto介面得到的透明圖加上背景色，所以需要輸入一張透明底png圖片
> > > > 请问单独调用 idphoto 接口 报的这个错是什么原因
> > 
> > 
> > 完整的调用接口方式代码，以及测试图片可以发一下，方便排查问题
> 
> 参数都是用默认的

大概知道了，是因为我没有给fastapi定义输入参数的类型，所以用swaggerUI调试会用问题，直接用cURL请求是可以的，我改一下

**Comment by Zeyi-Lin** [comment]
可以pull一下最新的代码，在swaggerUI再调试一下

**Comment by OuTaMan** [comment]
> 可以pull一下最新的代码，在swaggerUI再调试一下

好的 已经没问题了 谢谢
